import Link from "next/link";
import React from "react";
import { FaArrowLeft } from "react-icons/fa6";

const Blog = () => {
  return (
    <div className="bg-[#0b1120] min-h-screen relative text-gray-300">
      {/* Back Button */}
      <Link href={"/"} className="absolute flex hover:cursor-pointer z-10 justify-center items-center top-2 left-2 p-3 border border-white rounded-full bg-[#7F56D9] text-white">
        <FaArrowLeft size={20} />
      </Link>
      
      {/* Header Section */}
      <header className="py-12 sm:py-16 bg-gradient-to-r from-[#6C63FF] to-[#9472F2] text-white">
        <h1 className="text-4xl sm:text-6xl font-extrabold text-center tracking-wide">
          Welcome to <span className="text-[#E0E7FF]">My Blog</span>
        </h1>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-6 sm:px-10 py-10 sm:py-16 space-y-10 sm:space-y-16">
        {/* Introduction Section */}
        <section className="space-y-6">
          <h2 className="text-3xl sm:text-5xl font-bold text-white">
            Muhammad Yousuf – Full Stack Developer & Aspiring AI Engineer
          </h2>
          <p className="text-base sm:text-lg leading-relaxed">
            I’m Muhammad Yousuf, a passionate 19-year-old full-stack developer from Karachi, Pakistan, currently pursuing my education at Adamjee Science College. With a strong foundation in web development and a growing expertise in artificial intelligence (AI), I’ve spent the past year building dynamic web applications and expanding my knowledge in cutting-edge technologies. My ultimate goal? To become a leader in AI-driven web development and shape the future of digital experiences.
          </p>
        </section>

        {/* Journey Section */}
        <section className="space-y-6">
          <h3 className="text-2xl sm:text-4xl font-semibold text-[#CBACF9]">The Beginning of My Tech Journey</h3>
          <p className="text-base sm:text-lg leading-relaxed">
            My adventure in technology started when I joined the Governor Singh IT Program to study AI Engineering. This program ignited my curiosity and passion for coding, starting from the basics and quickly evolving into more advanced frameworks and languages. I began with HTML, CSS, and JavaScript, and soon moved on to TypeScript, React.js, Next.js, and Tailwind CSS. Alongside these front-end skills, I honed my expertise in MongoDB for the back end, and integrated powerful UI libraries like Shadcn for stunning, responsive designs.
          </p>
        </section>

        {/* Projects Section */}
        <section className="space-y-6">
          <h3 className="text-2xl sm:text-4xl font-semibold text-[#CBACF9]">Noteworthy Projects & Achievements</h3>
          <ul className="list-disc space-y-4 pl-5">
            <li>
              <strong>Amazon Homepage Clone:</strong> I recreated Amazon’s homepage using HTML, CSS, and JavaScript. This project showcases my skills in building responsive, user-friendly layouts that are visually appealing and functionally dynamic.
            </li>
            <li>
              <strong>Netflix Clone:</strong> Leveraging my expertise in front-end development, I developed a replica of Netflix’s user interface with interactive features such as hover effects and movie previews.
            </li>
            <li>
              <strong>Real-Time Weather App:</strong> Built using JavaScript, this app provides live weather data for any location worldwide, demonstrating my ability to integrate APIs and create real-time applications.
            </li>
            <li>
              <strong>AI-Powered Resume Builder:</strong> My full-stack skills shine in this Next.js project, where users can create, edit, and download resumes with AI-driven summaries generated by Wit.ai.
            </li>
            <li>
              <strong>Task Manager App:</strong> A user-friendly task management tool allowing users to organize and prioritize their daily tasks with an intuitive and clean interface.
            </li>
            <li>
              <strong>Music Library:</strong> A beautifully designed app for music enthusiasts to browse and organize their collections, featuring smooth animations and a visually appealing layout.
            </li>
          </ul>
        </section>

        {/* Excellence Section */}
        <section className="space-y-6">
          <h3 className="text-2xl sm:text-4xl font-semibold text-[#CBACF9]">Excellence in AI & Web Development</h3>
          <p className="text-base sm:text-lg leading-relaxed">
            I’ve been selected among the top 50 senior students in my AI program, chosen from over 1,500 peers. This achievement motivates me to continue excelling in AI engineering and full-stack development.
          </p>
        </section>

        {/* Looking Ahead Section */}
        <section className="space-y-6">
          <h3 className="text-2xl sm:text-4xl font-semibold text-[#CBACF9]">Future Goals: Merging AI and Web Development</h3>
          <p className="text-base sm:text-lg leading-relaxed">
            Looking ahead, I’m excited to deepen my expertise in Artificial Intelligence and Data Science, aiming to merge these advanced technologies with web development. This will enable me to create smarter, more intuitive websites and applications that redefine user experiences. 
          </p>
          <p className="text-base sm:text-lg leading-relaxed">
            Thank you for reading my journey! Feel free to explore my portfolio or reach out for collaboration. Let’s build something groundbreaking together!
          </p>
        </section>
      </main>

      {/* Footer Section */}
      <footer className="py-6 sm:py-8 bg-[#1a1f36] text-gray-400 text-center">
        <p>&copy; 2024 Muhammad Yousuf. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default Blog;
